name: Display README

on:
  push:
    branches:
      - main  # Thay thế "main" bằng tên nhánh chính của bạn

jobs:
  display-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Display README
      run: echo "<meta http-equiv='refresh' content='0;url=README.md'>" > index.html
